= Power Catch-up – Everything Practical and Important in Java 9 to 13

This repository is a HTML5 https://asciidoctor.org/[Asciidoctor] / 
https://asciidoctor.org/docs/asciidoctor-revealjs[Asciidoctor-RevealJS]
based presentation about everyting new and important since Java 8.

== Abstract
Since Java 9, it's all happening fast: In the 6-month cycle, Oracle releases new major versions, so that one can easily lose track of things. Due to the changed support model, many projects are likely to get in touch with Java versions beyond the long-established "eight" in 2019. Time for us professionals to get up to speed in a concentrated power session!

This session tries to provide a structured overall overview of the changes from Java 9 to 13 and at the same time to emphasize the important and relevant innovations in concrete examples. For example, we learn why collections are now doing better, that variables and `case` statements have gained new opportunities in the Model Contest and how Microbenchmark Suite and Flight Recorder are helping to identify performance issues. We also do not hide from our fears and learn how serious it is about eliminating `finalize()` or problems with jigsaw and how `jdeps` can help us with the upgrade from nasty surprises.

A quick look at the current status of JDK14 + helps with personal needs planning for the next fitness session. 

== Slides
Can be found online at https://bentolor.github.io/java9to13/

The sources are in `docs`

For licensing details see the accompagning `LICENCE` file in the directory.

== Example code
Mostly used to test/present different code. To run set your `JDK_HOME` to a 
Java 13+ installation and run with `./gradlew test`

For licensing details see the accompagning `LICENCE` file in the directory.
