== Performance

* Generally speaking: Every JDK after 8 is faster. Even if you do not make any changes you should be faster
** Memory usage: Compact String 
** Newer / improved GC

=== Benchmarking

*  v12: **Microbenchmark Suite based on JMH**, [jep]#https://openjdk.java.net/jeps/230[JEP 230]#
* Low-Overhead Heap Profiling via JMTI, [jep]#https://openjdk.java.net/jeps/331[JEP 331]#

=== Garbage Collectors

|===
| JDK | JEP | Change
| 9 | JEP248 | G1 default GC
| 10 | JEP307 | Parallel Full GC for G1
| 11 | JEP318 | Epsilon (Experimental)
| 11 | JEP333 | ZGC (Experimental. Formerly commercial)
| 12 | JEP180 | Shenandoah (Experimental)
| 12 | ?? | More Updates to G1
| 12 | ?? | More Improvements to ZGC
|===

v11

*    Low Latency Garbage Collector ZGC
*    Epsilon GC - no garbage collection at all
*    Based on Garbage Collector Interface (Java 10)


*    G1 Garbage Collector is now the default instead of Parallel GC
    JDK 9 https://openjdk.java.net/jeps/248

*    G1 GC performance improvements: Parallel Full GC to improve worst-case latencies
    JDK 10 https://openjdk.java.net/jeps/307

*    Introduce the Z Garbage Collector, which offers very low pause times on large heaps
    JDK 11 https://openjdk.java.net/jeps/333

*    Introduce the Epsilon Garbage Collector, which does not implement actual memory reclamation, striving for the lowest overhead possible
    JDK 10 https://openjdk.java.net/jeps/304 , JDK 11 https://openjdk.java.net/jeps/318

*    XX:AllocateHeapAt=<path> to support Alternative Memory Devices
    JDK 10 https://openjdk.java.net/jeps/316

*    Coming in JDK 12: G1 GC performance improvements: abortable mixed collections to meet user-supplied pause goals, automatically return Java heap memory to the operating system when idle
    JEP 344 https://openjdk.java.net/jeps/344 , JEP 346 https://openjdk.java.net/jeps/346

*    Coming in JDK 12: Introduce the Shenandoah Garbage Collector, offering similar benefits as ZGC but based on a different algorithm
    JEP 189 https://openjdk.java.net/jeps/189

=== Constable v12

https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/lang/constant/Constable.html


==== General

*    Space-efficient, Compact Strings that stores Latin-1 only Strings more efficiently
    JDK 9 https://openjdk.java.net/jeps/254

*    Code caches of profiled and non-profiled compiled code is separated, resulting in improved performance and memory footprint
    JDK 9 https://openjdk.java.net/jeps/197

 *   Store Interned Strings in Class-Data Sharing archives to reduce memory consumption
    JDK 9 https://openjdk.java.net/jeps/250

*    Application Class-Data Sharing to improve startup time and reduce footprint by sharing class metadata between Java processes.
    JDK 10 https://openjdk.java.net/jeps/310

*    Coming in JDK 12: Class-Data Sharing archive of the default class list is enabled by default to improve out-of-the-box startup time
    JEP 341 https://openjdk.java.net/jeps/341


==== Library related

*    Improved intrinsics for java.lang.Math sin, cos and log functions on AArch64 processors
    JDK 11

*    Security Manager performance improvements
    JDK 9

*    Spin-Wait Hint (Thread#onSpinWait) to optimize busy-waiting style loops
    JDK 9

*    Use Marlin Renderer in Java 2D as the default graphics rasterizer instead of Pisces
    JDK 9

 *   Improved GHASH and RSA performance by leveraging recently-introduced SPARC and Intel x64 CPU instructions
    JDK 9

==== Concurrency

*    Improved performance of contended object monitors
    JDK 9

*    Extra space on thread stack for critical sections, mitigating the risk of a deadlock in java.util.concurrent locks in case of a stack overflow
    JDK 9

 *   Thread-Local Handshakes to stop individual threads
    JDK 10 https://openjdk.java.net/jeps/312

==== Bytecode


*    Bytecode generated for static String-concatenation uses invokedynamic rather than directly creating StringBuilder#append chains. This will enable future optimizations of String concatenation without requiring bytecode changes.
    JDK 9

*    INVOKEDYNAMIC can express high-level operations on object properties and or collections
    JDK 9

*   CONSTANT_Dynamic constant-pool entry which uses bootstrapping to perform the resolution, similarly to INVOKEDYNAMIC calls
    JDK 11

*   Introduction of the Nest access-control context that wraps classes in the same code entity - such as nested classes - and eliminates the need for compiler to insert bridge methods to the generated bytecode.
    JDK 11

*    Coming in JDK 12: java.lang.invoke.constant package to allow easy description of loadable constants (operands for the ldc instruction), which is less error-prone than relying on ad-hoc String representation
    JEP 334


